"""Create initial tables

Revision ID: 082c981ad693
Revises: 
Create Date: 2026-03-09 18:59:00.481273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082c981ad693'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('workbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workbooks_id'), 'workbooks', ['id'], unique=False)
    op.create_index(op.f('ix_workbooks_workbook_id'), 'workbooks', ['workbook_id'], unique=False)
    op.create_table('worksheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('workbook_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workbook_id'], ['workbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheets_id'), 'worksheets', ['id'], unique=False)
    op.create_index(op.f('ix_worksheets_workbook_id'), 'worksheets', ['workbook_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('worksheet_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('edited_answer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_creator', 'questions', ['id', 'created_by'], unique=False)
    op.create_index(op.f('ix_questions_created_by'), 'questions', ['created_by'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_worksheet_id'), 'questions', ['worksheet_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_teacher_question', 'grades', ['teacher_id', 'answer_id'], unique=False)
    op.create_index(op.f('ix_grades_answer_id'), 'grades', ['answer_id'], unique=False)
    op.create_index(op.f('ix_grades_approved'), 'grades', ['approved'], unique=False)
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_teacher_id'), 'grades', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_teacher_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_approved'), table_name='grades')
    op.drop_index(op.f('ix_grades_answer_id'), table_name='grades')
    op.drop_index('idx_teacher_question', table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_questions_worksheet_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_by'), table_name='questions')
    op.drop_index('idx_question_creator', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_worksheets_workbook_id'), table_name='worksheets')
    op.drop_index(op.f('ix_worksheets_id'), table_name='worksheets')
    op.drop_table('worksheets')
    op.drop_index(op.f('ix_workbooks_workbook_id'), table_name='workbooks')
    op.drop_index(op.f('ix_workbooks_id'), table_name='workbooks')
    op.drop_table('workbooks')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
