"""Align models with current code

Revision ID: 4b0350253acd
Revises: 082c981ad693
Create Date: 2026-03-09 22:36:24.648954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0350253acd'
down_revision: Union[str, Sequence[str], None] = '082c981ad693'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_student_id'), 'answers', ['student_id'], unique=False)
    op.drop_index(op.f('idx_teacher_question'), table_name='grades')
    op.create_index('idx_teacher_answer', 'grades', ['teacher_id', 'answer_id'], unique=False)
    op.drop_constraint(op.f('grades_answer_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'answers', ['answer_id'], ['id'])
    op.drop_column('questions', 'answer_text')
    op.drop_column('questions', 'edited_answer')
    op.add_column('workbooks', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_workbooks_workbook_id'), table_name='workbooks')
    op.create_index(op.f('ix_workbooks_created_by'), 'workbooks', ['created_by'], unique=False)
    op.drop_constraint(op.f('workbooks_workbook_id_fkey'), 'workbooks', type_='foreignkey')
    op.create_foreign_key(None, 'workbooks', 'users', ['created_by'], ['id'])
    op.drop_column('workbooks', 'workbook_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workbooks', sa.Column('workbook_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workbooks', type_='foreignkey')
    op.create_foreign_key(op.f('workbooks_workbook_id_fkey'), 'workbooks', 'users', ['workbook_id'], ['id'])
    op.drop_index(op.f('ix_workbooks_created_by'), table_name='workbooks')
    op.create_index(op.f('ix_workbooks_workbook_id'), 'workbooks', ['workbook_id'], unique=False)
    op.drop_column('workbooks', 'created_by')
    op.add_column('questions', sa.Column('edited_answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_answer_id_fkey'), 'grades', 'questions', ['answer_id'], ['id'])
    op.drop_index('idx_teacher_answer', table_name='grades')
    op.create_index(op.f('idx_teacher_question'), 'grades', ['teacher_id', 'answer_id'], unique=False)
    op.drop_index(op.f('ix_answers_student_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
